server:
  port: 8001
spring:
  application:
    name: @project.name@
  cloud:
    config:
      profile: @env@
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
management:
  security:
    enabled: false
